#![doc = "Peripheral access API for MAX78002 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 3;
pub use cortex_m::peripheral::Peripherals as CorePeripherals;
pub use cortex_m::peripheral::{CBP, CPUID, DCB, DWT, FPB, FPU, ITM, MPU, NVIC, SCB, SYST, TPIU};
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn PF();
    fn WDT0();
    fn USB();
    fn RTC();
    fn TRNG();
    fn TMR0();
    fn TMR1();
    fn TMR2();
    fn TMR3();
    fn TMR4();
    fn TMR5();
    fn I2C0();
    fn UART0();
    fn UART1();
    fn SPI1();
    fn ADC();
    fn FLC0();
    fn GPIO0();
    fn GPIO1();
    fn GPIO2();
    fn DMA0();
    fn DMA1();
    fn DMA2();
    fn DMA3();
    fn UART2();
    fn I2C1();
    fn WUT();
    fn GPIOWAKE();
    fn SPI0();
    fn WDT1();
    fn PT();
    fn I2C2();
    fn SDHC();
    fn OWM();
    fn DMA4();
    fn DMA5();
    fn DMA6();
    fn DMA7();
    fn DMA8();
    fn DMA9();
    fn DMA10();
    fn DMA11();
    fn DMA12();
    fn DMA13();
    fn DMA14();
    fn DMA15();
    fn USBDMA();
    fn DVS();
    fn SIMO();
    fn UART3();
    fn PCIF();
    fn AES();
    fn CRC();
    fn I2S();
    fn LPCMP();
    fn CSI2();
    fn CNN_FIFO();
    fn CNN();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 118] = [
    Vector { _handler: PF },
    Vector { _handler: WDT0 },
    Vector { _handler: USB },
    Vector { _handler: RTC },
    Vector { _handler: TRNG },
    Vector { _handler: TMR0 },
    Vector { _handler: TMR1 },
    Vector { _handler: TMR2 },
    Vector { _handler: TMR3 },
    Vector { _handler: TMR4 },
    Vector { _handler: TMR5 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: I2C0 },
    Vector { _handler: UART0 },
    Vector { _handler: UART1 },
    Vector { _handler: SPI1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: ADC },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: FLC0 },
    Vector { _handler: GPIO0 },
    Vector { _handler: GPIO1 },
    Vector { _handler: GPIO2 },
    Vector { _reserved: 0 },
    Vector { _handler: DMA0 },
    Vector { _handler: DMA1 },
    Vector { _handler: DMA2 },
    Vector { _handler: DMA3 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: UART2 },
    Vector { _reserved: 0 },
    Vector { _handler: I2C1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: WUT },
    Vector { _handler: GPIOWAKE },
    Vector { _reserved: 0 },
    Vector { _handler: SPI0 },
    Vector { _handler: WDT1 },
    Vector { _reserved: 0 },
    Vector { _handler: PT },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: I2C2 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: SDHC },
    Vector { _handler: OWM },
    Vector { _handler: DMA4 },
    Vector { _handler: DMA5 },
    Vector { _handler: DMA6 },
    Vector { _handler: DMA7 },
    Vector { _handler: DMA8 },
    Vector { _handler: DMA9 },
    Vector { _handler: DMA10 },
    Vector { _handler: DMA11 },
    Vector { _handler: DMA12 },
    Vector { _handler: DMA13 },
    Vector { _handler: DMA14 },
    Vector { _handler: DMA15 },
    Vector { _handler: USBDMA },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: DVS },
    Vector { _handler: SIMO },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: UART3 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: PCIF },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: AES },
    Vector { _handler: CRC },
    Vector { _handler: I2S },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: LPCMP },
    Vector { _handler: CSI2 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: CNN_FIFO },
    Vector { _handler: CNN },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - PF"]
    PF = 0,
    #[doc = "1 - WDT0"]
    WDT0 = 1,
    #[doc = "2 - USB"]
    USB = 2,
    #[doc = "3 - RTC interrupt."]
    RTC = 3,
    #[doc = "4 - TRNG interrupt."]
    TRNG = 4,
    #[doc = "5 - TMR0"]
    TMR0 = 5,
    #[doc = "6 - TMR1 IRQ"]
    TMR1 = 6,
    #[doc = "7 - TMR2 IRQ"]
    TMR2 = 7,
    #[doc = "8 - TMR3 IRQ"]
    TMR3 = 8,
    #[doc = "9 - TMR4 IRQ"]
    TMR4 = 9,
    #[doc = "10 - TMR5 IRQ"]
    TMR5 = 10,
    #[doc = "13 - I2C0 IRQ"]
    I2C0 = 13,
    #[doc = "14 - UART0"]
    UART0 = 14,
    #[doc = "15 - UART1"]
    UART1 = 15,
    #[doc = "16 - SPI1 IRQ"]
    SPI1 = 16,
    #[doc = "20 - ADC IRQ"]
    ADC = 20,
    #[doc = "23 - Flash Controller interrupt."]
    FLC0 = 23,
    #[doc = "24 - GPIO0 interrupt."]
    GPIO0 = 24,
    #[doc = "25 - GPIO1 IRQ"]
    GPIO1 = 25,
    #[doc = "26 - GPIO2 IRQ"]
    GPIO2 = 26,
    #[doc = "28 - DMA0"]
    DMA0 = 28,
    #[doc = "29 - DMA1"]
    DMA1 = 29,
    #[doc = "30 - DMA2"]
    DMA2 = 30,
    #[doc = "31 - DMA3"]
    DMA3 = 31,
    #[doc = "34 - UART2"]
    UART2 = 34,
    #[doc = "36 - I2C1 IRQ"]
    I2C1 = 36,
    #[doc = "53 - WUT"]
    WUT = 53,
    #[doc = "54 - GPIOWAKE"]
    GPIOWAKE = 54,
    #[doc = "56 - SPI0"]
    SPI0 = 56,
    #[doc = "57 - WDT1 IRQ"]
    WDT1 = 57,
    #[doc = "59 - Pulse Train IRQ"]
    PT = 59,
    #[doc = "62 - I2C2 IRQ"]
    I2C2 = 62,
    #[doc = "66 - SDHC"]
    SDHC = 66,
    #[doc = "67 - OWM"]
    OWM = 67,
    #[doc = "68 - DMA4"]
    DMA4 = 68,
    #[doc = "69 - DMA5"]
    DMA5 = 69,
    #[doc = "70 - DMA6"]
    DMA6 = 70,
    #[doc = "71 - DMA7"]
    DMA7 = 71,
    #[doc = "72 - DMA8"]
    DMA8 = 72,
    #[doc = "73 - DMA9"]
    DMA9 = 73,
    #[doc = "74 - DMA10"]
    DMA10 = 74,
    #[doc = "75 - DMA11"]
    DMA11 = 75,
    #[doc = "76 - DMA12"]
    DMA12 = 76,
    #[doc = "77 - DMA13"]
    DMA13 = 77,
    #[doc = "78 - DMA14"]
    DMA14 = 78,
    #[doc = "79 - DMA15"]
    DMA15 = 79,
    #[doc = "80 - USBDMA"]
    USBDMA = 80,
    #[doc = "83 - Dynamic Voltage Scaling Interrupt"]
    DVS = 83,
    #[doc = "84 - SIMO"]
    SIMO = 84,
    #[doc = "88 - UART3"]
    UART3 = 88,
    #[doc = "91 - PCIF"]
    PCIF = 91,
    #[doc = "97 - AES"]
    AES = 97,
    #[doc = "98 - CRC"]
    CRC = 98,
    #[doc = "99 - I2S IRQ"]
    I2S = 99,
    #[doc = "103 - Low Power Comparato"]
    LPCMP = 103,
    #[doc = "104 - CSI2"]
    CSI2 = 104,
    #[doc = "116 - CNN accelerator fast FIFO."]
    CNN_FIFO = 116,
    #[doc = "117 - CNN accelerator completion."]
    CNN = 117,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "Inter-Integrated Circuit."]
pub type Adc = crate::Periph<adc::RegisterBlock, 0x4003_4000>;
impl core::fmt::Debug for Adc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc").finish()
    }
}
#[doc = "Inter-Integrated Circuit."]
pub mod adc;
#[doc = "AES Keys."]
pub type Aes = crate::Periph<aes::RegisterBlock, 0x4000_7400>;
impl core::fmt::Debug for Aes {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aes").finish()
    }
}
#[doc = "AES Keys."]
pub mod aes;
#[doc = "AES Key Registers."]
pub type Aeskeys = crate::Periph<aeskeys::RegisterBlock, 0x4000_7800>;
impl core::fmt::Debug for Aeskeys {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aeskeys").finish()
    }
}
#[doc = "AES Key Registers."]
pub mod aeskeys;
#[doc = "Parallel Camera Interface."]
pub type Cameraif = crate::Periph<cameraif::RegisterBlock, 0x4000_e000>;
impl core::fmt::Debug for Cameraif {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cameraif").finish()
    }
}
#[doc = "Parallel Camera Interface."]
pub mod cameraif;
#[doc = "CRC Registers."]
pub type Crc = crate::Periph<crc::RegisterBlock, 0x4000_f000>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
#[doc = "CRC Registers."]
pub mod crc;
#[doc = "Camera Serial Interface Registers."]
pub type Csi2 = crate::Periph<csi2::RegisterBlock, 0x4006_2000>;
impl core::fmt::Debug for Csi2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Csi2").finish()
    }
}
#[doc = "Camera Serial Interface Registers."]
pub mod csi2;
#[doc = "DMA Controller Fully programmable, chaining capable DMA channels."]
pub type Dma = crate::Periph<dma::RegisterBlock, 0x4002_8000>;
impl core::fmt::Debug for Dma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma").finish()
    }
}
#[doc = "DMA Controller Fully programmable, chaining capable DMA channels."]
pub mod dma;
#[doc = "Dynamic Voltage Scaling"]
pub type Dvs = crate::Periph<dvs::RegisterBlock, 0x4000_3c00>;
impl core::fmt::Debug for Dvs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dvs").finish()
    }
}
#[doc = "Dynamic Voltage Scaling"]
pub mod dvs;
#[doc = "Function Control Register."]
pub type Fcr = crate::Periph<fcr::RegisterBlock, 0x4000_0800>;
impl core::fmt::Debug for Fcr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Fcr").finish()
    }
}
#[doc = "Function Control Register."]
pub mod fcr;
#[doc = "Flash Memory Control."]
pub type Flc = crate::Periph<flc::RegisterBlock, 0x4002_9000>;
impl core::fmt::Debug for Flc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flc").finish()
    }
}
#[doc = "Flash Memory Control."]
pub mod flc;
#[doc = "Global Control Registers."]
pub type Gcr = crate::Periph<gcr::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Gcr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gcr").finish()
    }
}
#[doc = "Global Control Registers."]
pub mod gcr;
#[doc = "Global Control Function Register."]
pub type Gcfr = crate::Periph<gcfr::RegisterBlock, 0x4000_5800>;
impl core::fmt::Debug for Gcfr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gcfr").finish()
    }
}
#[doc = "Global Control Function Register."]
pub mod gcfr;
#[doc = "Individual I/O for each GPIO"]
pub type Gpio0 = crate::Periph<gpio0::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Gpio0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio0").finish()
    }
}
#[doc = "Individual I/O for each GPIO"]
pub mod gpio0;
#[doc = "Individual I/O for each GPIO 1"]
pub type Gpio1 = crate::Periph<gpio0::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Gpio1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio1").finish()
    }
}
#[doc = "Individual I/O for each GPIO 1"]
pub use self::gpio0 as gpio1;
#[doc = "Individual I/O for each GPIO 2"]
pub type Gpio2 = crate::Periph<gpio0::RegisterBlock, 0x4008_0400>;
impl core::fmt::Debug for Gpio2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio2").finish()
    }
}
#[doc = "Individual I/O for each GPIO 2"]
pub use self::gpio0 as gpio2;
#[doc = "Inter-Integrated Circuit."]
pub type I2c0 = crate::Periph<i2c0::RegisterBlock, 0x4001_d000>;
impl core::fmt::Debug for I2c0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c0").finish()
    }
}
#[doc = "Inter-Integrated Circuit."]
pub mod i2c0;
#[doc = "Inter-Integrated Circuit. 1"]
pub type I2c1 = crate::Periph<i2c0::RegisterBlock, 0x4001_e000>;
impl core::fmt::Debug for I2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1").finish()
    }
}
#[doc = "Inter-Integrated Circuit. 1"]
pub use self::i2c0 as i2c1;
#[doc = "Inter-Integrated Circuit. 2"]
pub type I2c2 = crate::Periph<i2c0::RegisterBlock, 0x4001_f000>;
impl core::fmt::Debug for I2c2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c2").finish()
    }
}
#[doc = "Inter-Integrated Circuit. 2"]
pub use self::i2c0 as i2c2;
#[doc = "Inter-IC Sound Interface."]
pub type I2s = crate::Periph<i2s::RegisterBlock, 0x4006_0000>;
impl core::fmt::Debug for I2s {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s").finish()
    }
}
#[doc = "Inter-IC Sound Interface."]
pub mod i2s;
#[doc = "Instruction Cache Controller Registers"]
pub type Icc0 = crate::Periph<icc0::RegisterBlock, 0x4002_a000>;
impl core::fmt::Debug for Icc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Icc0").finish()
    }
}
#[doc = "Instruction Cache Controller Registers"]
pub mod icc0;
#[doc = "Instruction Cache Controller Registers 1"]
pub type Icc1 = crate::Periph<icc0::RegisterBlock, 0x4002_ac00>;
impl core::fmt::Debug for Icc1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Icc1").finish()
    }
}
#[doc = "Instruction Cache Controller Registers 1"]
pub use self::icc0 as icc1;
#[doc = "Low Power Comparator"]
pub type Lpcmp = crate::Periph<lpcmp::RegisterBlock, 0x4008_8000>;
impl core::fmt::Debug for Lpcmp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpcmp").finish()
    }
}
#[doc = "Low Power Comparator"]
pub mod lpcmp;
#[doc = "Low Power Global Control."]
pub type Lpgcr = crate::Periph<lpgcr::RegisterBlock, 0x4008_0000>;
impl core::fmt::Debug for Lpgcr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpgcr").finish()
    }
}
#[doc = "Low Power Global Control."]
pub mod lpgcr;
#[doc = "Misc Control."]
pub type Mcr = crate::Periph<mcr::RegisterBlock, 0x4000_6c00>;
impl core::fmt::Debug for Mcr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mcr").finish()
    }
}
#[doc = "Misc Control."]
pub mod mcr;
#[doc = "1-Wire Master Interface."]
pub type Owm = crate::Periph<owm::RegisterBlock, 0x4003_d000>;
impl core::fmt::Debug for Owm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Owm").finish()
    }
}
#[doc = "1-Wire Master Interface."]
pub mod owm;
#[doc = "Pulse Train"]
pub type Pt0 = crate::Periph<pt0::RegisterBlock, 0x4003_c020>;
impl core::fmt::Debug for Pt0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pt0").finish()
    }
}
#[doc = "Pulse Train"]
pub mod pt0;
#[doc = "Pulse Train 1"]
pub type Pt1 = crate::Periph<pt0::RegisterBlock, 0x4003_c030>;
impl core::fmt::Debug for Pt1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pt1").finish()
    }
}
#[doc = "Pulse Train 1"]
pub use self::pt0 as pt1;
#[doc = "Pulse Train 2"]
pub type Pt2 = crate::Periph<pt0::RegisterBlock, 0x4003_c040>;
impl core::fmt::Debug for Pt2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pt2").finish()
    }
}
#[doc = "Pulse Train 2"]
pub use self::pt0 as pt2;
#[doc = "Pulse Train 3"]
pub type Pt3 = crate::Periph<pt0::RegisterBlock, 0x4003_c050>;
impl core::fmt::Debug for Pt3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pt3").finish()
    }
}
#[doc = "Pulse Train 3"]
pub use self::pt0 as pt3;
#[doc = "Pulse Train Generation"]
pub type Ptg = crate::Periph<ptg::RegisterBlock, 0x4003_c000>;
impl core::fmt::Debug for Ptg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ptg").finish()
    }
}
#[doc = "Pulse Train Generation"]
pub mod ptg;
#[doc = "Power Sequencer / Low Power Control Register."]
pub type Pwrseq = crate::Periph<pwrseq::RegisterBlock, 0x4000_6800>;
impl core::fmt::Debug for Pwrseq {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwrseq").finish()
    }
}
#[doc = "Power Sequencer / Low Power Control Register."]
pub mod pwrseq;
#[doc = "Real Time Clock and Alarm."]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "Real Time Clock and Alarm."]
pub mod rtc;
#[doc = "SDHC/SDIO Controller"]
pub type Sdhc = crate::Periph<sdhc::RegisterBlock, 0x4003_7000>;
impl core::fmt::Debug for Sdhc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sdhc").finish()
    }
}
#[doc = "SDHC/SDIO Controller"]
pub mod sdhc;
#[doc = "The Semaphore peripheral allows multiple cores in a system to cooperate when accessing shred resources. The peripheral contains eight semaphores that can be atomically set and cleared. It is left to the discretion of the software architect to decide how and when the semaphores are used and how they are allocated. Existing hardware does not have to be modified for this type of cooperative sharing, and the use of semaphores is exclusively within the software domain."]
pub type Sema = crate::Periph<sema::RegisterBlock, 0x4003_e000>;
impl core::fmt::Debug for Sema {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sema").finish()
    }
}
#[doc = "The Semaphore peripheral allows multiple cores in a system to cooperate when accessing shred resources. The peripheral contains eight semaphores that can be atomically set and cleared. It is left to the discretion of the software architect to decide how and when the semaphores are used and how they are allocated. Existing hardware does not have to be modified for this type of cooperative sharing, and the use of semaphores is exclusively within the software domain."]
pub mod sema;
#[doc = "Single Inductor Multiple Output Switching Converter"]
pub type Simo = crate::Periph<simo::RegisterBlock, 0x4000_4400>;
impl core::fmt::Debug for Simo {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Simo").finish()
    }
}
#[doc = "Single Inductor Multiple Output Switching Converter"]
pub mod simo;
#[doc = "System Initialization Registers."]
pub type Sir = crate::Periph<sir::RegisterBlock, 0x4000_0400>;
impl core::fmt::Debug for Sir {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sir").finish()
    }
}
#[doc = "System Initialization Registers."]
pub mod sir;
#[doc = "SPI peripheral."]
pub type Spi0 = crate::Periph<spi0::RegisterBlock, 0x400b_e000>;
impl core::fmt::Debug for Spi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi0").finish()
    }
}
#[doc = "SPI peripheral."]
pub mod spi0;
#[doc = "CNN accelerator fast FIFO. A separate APB peripheral from the CNN block, used as a high-rate input path to the accelerator."]
pub type CnnFifo = crate::Periph<cnn_fifo::RegisterBlock, 0x400c_0400>;
impl core::fmt::Debug for CnnFifo {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CnnFifo").finish()
    }
}
#[doc = "CNN accelerator fast FIFO. A separate APB peripheral from the CNN block, used as a high-rate input path to the accelerator."]
pub mod cnn_fifo;
#[doc = "Convolutional Neural Network Accelerator, global control."]
pub type Cnn = crate::Periph<cnn::RegisterBlock, 0x5000_0000>;
impl core::fmt::Debug for Cnn {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cnn").finish()
    }
}
#[doc = "Convolutional Neural Network Accelerator, global control."]
pub mod cnn;
#[doc = "CNNx16 quadrant 0 control."]
pub type Cnnx16_0 = crate::Periph<cnnx16_0::RegisterBlock, 0x5100_0000>;
impl core::fmt::Debug for Cnnx16_0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cnnx16_0").finish()
    }
}
#[doc = "CNNx16 quadrant 0 control."]
pub mod cnnx16_0;
#[doc = "CNNx16 quadrant 1 control."]
pub type Cnnx16_1 = crate::Periph<cnnx16_0::RegisterBlock, 0x5200_0000>;
impl core::fmt::Debug for Cnnx16_1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cnnx16_1").finish()
    }
}
#[doc = "CNNx16 quadrant 1 control."]
pub use self::cnnx16_0 as cnnx16_1;
#[doc = "CNNx16 quadrant 2 control."]
pub type Cnnx16_2 = crate::Periph<cnnx16_0::RegisterBlock, 0x5300_0000>;
impl core::fmt::Debug for Cnnx16_2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cnnx16_2").finish()
    }
}
#[doc = "CNNx16 quadrant 2 control."]
pub use self::cnnx16_0 as cnnx16_2;
#[doc = "CNNx16 quadrant 3 control."]
pub type Cnnx16_3 = crate::Periph<cnnx16_0::RegisterBlock, 0x5400_0000>;
impl core::fmt::Debug for Cnnx16_3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cnnx16_3").finish()
    }
}
#[doc = "CNNx16 quadrant 3 control."]
pub use self::cnnx16_0 as cnnx16_3;
#[doc = "SPI peripheral. 1"]
pub type Spi1 = crate::Periph<spi0::RegisterBlock, 0x4004_6000>;
impl core::fmt::Debug for Spi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi1").finish()
    }
}
#[doc = "SPI peripheral. 1"]
pub use self::spi0 as spi1;
#[doc = "Low-Power Configurable Timer"]
pub type Tmr0 = crate::Periph<tmr0::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Tmr0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr0").finish()
    }
}
#[doc = "Low-Power Configurable Timer"]
pub mod tmr0;
#[doc = "Low-Power Configurable Timer 1"]
pub type Tmr1 = crate::Periph<tmr0::RegisterBlock, 0x4001_1000>;
impl core::fmt::Debug for Tmr1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr1").finish()
    }
}
#[doc = "Low-Power Configurable Timer 1"]
pub use self::tmr0 as tmr1;
#[doc = "Low-Power Configurable Timer 2"]
pub type Tmr2 = crate::Periph<tmr0::RegisterBlock, 0x4001_2000>;
impl core::fmt::Debug for Tmr2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr2").finish()
    }
}
#[doc = "Low-Power Configurable Timer 2"]
pub use self::tmr0 as tmr2;
#[doc = "Low-Power Configurable Timer 3"]
pub type Tmr3 = crate::Periph<tmr0::RegisterBlock, 0x4001_3000>;
impl core::fmt::Debug for Tmr3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr3").finish()
    }
}
#[doc = "Low-Power Configurable Timer 3"]
pub use self::tmr0 as tmr3;
#[doc = "Low-Power Configurable Timer 4"]
pub type Tmr4 = crate::Periph<tmr0::RegisterBlock, 0x4008_0c00>;
impl core::fmt::Debug for Tmr4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr4").finish()
    }
}
#[doc = "Low-Power Configurable Timer 4"]
pub use self::tmr0 as tmr4;
#[doc = "Low-Power Configurable Timer 5"]
pub type Tmr5 = crate::Periph<tmr0::RegisterBlock, 0x4008_1000>;
impl core::fmt::Debug for Tmr5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr5").finish()
    }
}
#[doc = "Low-Power Configurable Timer 5"]
pub use self::tmr0 as tmr5;
#[doc = "Random Number Generator."]
pub type Trng = crate::Periph<trng::RegisterBlock, 0x4004_d000>;
impl core::fmt::Debug for Trng {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Trng").finish()
    }
}
#[doc = "Random Number Generator."]
pub mod trng;
#[doc = "Trim System Initilazation Registers"]
pub type Trimsir = crate::Periph<trimsir::RegisterBlock, 0x4000_5400>;
impl core::fmt::Debug for Trimsir {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Trimsir").finish()
    }
}
#[doc = "Trim System Initilazation Registers"]
pub mod trimsir;
#[doc = "UART Low Power Registers"]
pub type Uart0 = crate::Periph<uart0::RegisterBlock, 0x4004_2000>;
impl core::fmt::Debug for Uart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0").finish()
    }
}
#[doc = "UART Low Power Registers"]
pub mod uart0;
#[doc = "UART Low Power Registers 1"]
pub type Uart1 = crate::Periph<uart0::RegisterBlock, 0x4004_3000>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
#[doc = "UART Low Power Registers 1"]
pub use self::uart0 as uart1;
#[doc = "UART Low Power Registers 2"]
pub type Uart2 = crate::Periph<uart0::RegisterBlock, 0x4004_4000>;
impl core::fmt::Debug for Uart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart2").finish()
    }
}
#[doc = "UART Low Power Registers 2"]
pub use self::uart0 as uart2;
#[doc = "UART Low Power Registers 3"]
pub type Uart3 = crate::Periph<uart0::RegisterBlock, 0x4008_1400>;
impl core::fmt::Debug for Uart3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart3").finish()
    }
}
#[doc = "UART Low Power Registers 3"]
pub use self::uart0 as uart3;
#[doc = "USB 2.0 High-speed Controller."]
pub type Usbhs = crate::Periph<usbhs::RegisterBlock, 0x400b_1000>;
impl core::fmt::Debug for Usbhs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usbhs").finish()
    }
}
#[doc = "USB 2.0 High-speed Controller."]
pub mod usbhs;
#[doc = "Windowed Watchdog Timer"]
pub type Wdt0 = crate::Periph<wdt0::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Wdt0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdt0").finish()
    }
}
#[doc = "Windowed Watchdog Timer"]
pub mod wdt0;
#[doc = "Windowed Watchdog Timer 1"]
pub type Wdt1 = crate::Periph<wdt0::RegisterBlock, 0x4008_0800>;
impl core::fmt::Debug for Wdt1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdt1").finish()
    }
}
#[doc = "Windowed Watchdog Timer 1"]
pub use self::wdt0 as wdt1;
#[doc = "Wake Up Timer"]
pub type Wut = crate::Periph<wut::RegisterBlock, 0x4000_6400>;
impl core::fmt::Debug for Wut {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wut").finish()
    }
}
#[doc = "Wake Up Timer"]
pub mod wut;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "ADC"]
    pub adc: Adc,
    #[doc = "AES"]
    pub aes: Aes,
    #[doc = "AESKEYS"]
    pub aeskeys: Aeskeys,
    #[doc = "CAMERAIF"]
    pub cameraif: Cameraif,
    #[doc = "CRC"]
    pub crc: Crc,
    #[doc = "CSI2"]
    pub csi2: Csi2,
    #[doc = "DMA"]
    pub dma: Dma,
    #[doc = "DVS"]
    pub dvs: Dvs,
    #[doc = "FCR"]
    pub fcr: Fcr,
    #[doc = "FLC"]
    pub flc: Flc,
    #[doc = "GCR"]
    pub gcr: Gcr,
    #[doc = "GCFR"]
    pub gcfr: Gcfr,
    #[doc = "GPIO0"]
    pub gpio0: Gpio0,
    #[doc = "GPIO1"]
    pub gpio1: Gpio1,
    #[doc = "GPIO2"]
    pub gpio2: Gpio2,
    #[doc = "I2C0"]
    pub i2c0: I2c0,
    #[doc = "I2C1"]
    pub i2c1: I2c1,
    #[doc = "I2C2"]
    pub i2c2: I2c2,
    #[doc = "I2S"]
    pub i2s: I2s,
    #[doc = "ICC0"]
    pub icc0: Icc0,
    #[doc = "ICC1"]
    pub icc1: Icc1,
    #[doc = "LPCMP"]
    pub lpcmp: Lpcmp,
    #[doc = "LPGCR"]
    pub lpgcr: Lpgcr,
    #[doc = "MCR"]
    pub mcr: Mcr,
    #[doc = "OWM"]
    pub owm: Owm,
    #[doc = "PT0"]
    pub pt0: Pt0,
    #[doc = "PT1"]
    pub pt1: Pt1,
    #[doc = "PT2"]
    pub pt2: Pt2,
    #[doc = "PT3"]
    pub pt3: Pt3,
    #[doc = "PTG"]
    pub ptg: Ptg,
    #[doc = "PWRSEQ"]
    pub pwrseq: Pwrseq,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "SDHC"]
    pub sdhc: Sdhc,
    #[doc = "SEMA"]
    pub sema: Sema,
    #[doc = "SIMO"]
    pub simo: Simo,
    #[doc = "SIR"]
    pub sir: Sir,
    #[doc = "SPI0"]
    pub spi0: Spi0,
    #[doc = "CNN_FIFO"]
    pub cnn_fifo: CnnFifo,
    #[doc = "CNN"]
    pub cnn: Cnn,
    #[doc = "CNNX16_0"]
    pub cnnx16_0: Cnnx16_0,
    #[doc = "CNNX16_1"]
    pub cnnx16_1: Cnnx16_1,
    #[doc = "CNNX16_2"]
    pub cnnx16_2: Cnnx16_2,
    #[doc = "CNNX16_3"]
    pub cnnx16_3: Cnnx16_3,
    #[doc = "SPI1"]
    pub spi1: Spi1,
    #[doc = "TMR0"]
    pub tmr0: Tmr0,
    #[doc = "TMR1"]
    pub tmr1: Tmr1,
    #[doc = "TMR2"]
    pub tmr2: Tmr2,
    #[doc = "TMR3"]
    pub tmr3: Tmr3,
    #[doc = "TMR4"]
    pub tmr4: Tmr4,
    #[doc = "TMR5"]
    pub tmr5: Tmr5,
    #[doc = "TRNG"]
    pub trng: Trng,
    #[doc = "TRIMSIR"]
    pub trimsir: Trimsir,
    #[doc = "UART0"]
    pub uart0: Uart0,
    #[doc = "UART1"]
    pub uart1: Uart1,
    #[doc = "UART2"]
    pub uart2: Uart2,
    #[doc = "UART3"]
    pub uart3: Uart3,
    #[doc = "USBHS"]
    pub usbhs: Usbhs,
    #[doc = "WDT0"]
    pub wdt0: Wdt0,
    #[doc = "WDT1"]
    pub wdt1: Wdt1,
    #[doc = "WUT"]
    pub wut: Wut,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            adc: Adc::steal(),
            aes: Aes::steal(),
            aeskeys: Aeskeys::steal(),
            cameraif: Cameraif::steal(),
            crc: Crc::steal(),
            csi2: Csi2::steal(),
            dma: Dma::steal(),
            dvs: Dvs::steal(),
            fcr: Fcr::steal(),
            flc: Flc::steal(),
            gcr: Gcr::steal(),
            gcfr: Gcfr::steal(),
            gpio0: Gpio0::steal(),
            gpio1: Gpio1::steal(),
            gpio2: Gpio2::steal(),
            i2c0: I2c0::steal(),
            i2c1: I2c1::steal(),
            i2c2: I2c2::steal(),
            i2s: I2s::steal(),
            icc0: Icc0::steal(),
            icc1: Icc1::steal(),
            lpcmp: Lpcmp::steal(),
            lpgcr: Lpgcr::steal(),
            mcr: Mcr::steal(),
            owm: Owm::steal(),
            pt0: Pt0::steal(),
            pt1: Pt1::steal(),
            pt2: Pt2::steal(),
            pt3: Pt3::steal(),
            ptg: Ptg::steal(),
            pwrseq: Pwrseq::steal(),
            rtc: Rtc::steal(),
            sdhc: Sdhc::steal(),
            sema: Sema::steal(),
            simo: Simo::steal(),
            sir: Sir::steal(),
            spi0: Spi0::steal(),
            cnn_fifo: CnnFifo::steal(),
            cnn: Cnn::steal(),
            cnnx16_0: Cnnx16_0::steal(),
            cnnx16_1: Cnnx16_1::steal(),
            cnnx16_2: Cnnx16_2::steal(),
            cnnx16_3: Cnnx16_3::steal(),
            spi1: Spi1::steal(),
            tmr0: Tmr0::steal(),
            tmr1: Tmr1::steal(),
            tmr2: Tmr2::steal(),
            tmr3: Tmr3::steal(),
            tmr4: Tmr4::steal(),
            tmr5: Tmr5::steal(),
            trng: Trng::steal(),
            trimsir: Trimsir::steal(),
            uart0: Uart0::steal(),
            uart1: Uart1::steal(),
            uart2: Uart2::steal(),
            uart3: Uart3::steal(),
            usbhs: Usbhs::steal(),
            wdt0: Wdt0::steal(),
            wdt1: Wdt1::steal(),
            wut: Wut::steal(),
        }
    }
}
